#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration,
# displays Best School and then Hi on a new line
i=1
msg='Best School'
while [ $i -le 10 ]
do
	if [ $i == 9 ]
	then
		echo "$msg";
		echo "Hi";
	else
		echo "$msg";
	fi;
	i=$((i+1));
done
