#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
i=1
a=4
b=9
c=17
while [ $i -le 20 ]
do
	echo $i
	case $i in
		$a)
			echo "bad luck from China";;
		$b)
			echo "bad luck from Japan";;
		$c)
			echo "bad luck from Italy";
	esac
	i=$((i+1));
done
