#!/usr/bin/env bash
# Display information about subdomains.

domn_conf () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

if [ "$#" == 1 ]
then
  domn_conf "$1" "www"
  domn_conf "$1" "lb-01"
  domn_conf "$1" "web-01"
  domn_conf "$1" "web-02"
elif [ "$#" == 2 ]
then
  domn_conf "$1" "$2"
fi
