#!/usr/bin/env bash
value=$(</etc/passwd)
for i in $value
do
	echo "$i" | cut -d'-' -f2
	break
done
echo 1,2,3,4,5,6,7,8,9,...100 | cut -d, -f-4,6-6,8-
echo root:x:0:0:root:/root:/bin/bash | cut -d: -f-3, 6-6
