#!/usr/bin/env bash
file="/etc/passwd"
while read -r line
do
	msg=""
	msg2=$( echo "$line" | cut -d':' -f 1-1 )
        msg3=$( echo "$line" | cut -d':' -f 3-3 )
        msg4=$( echo "$line" | cut -d':' -f 6 )
        msg+="${msg2}"
        msg+=':'
        msg+="${msg3}"
        msg+=':'
        msg+="${msg4}"
	echo "$msg"
done < $file
